hparams = {'batch_size': 64,
           'vocab_size': 50000,
           'maxlen': 512,
           'learning_rate': 0.001,
           'beta_1': 0.9,
           'beta_2': 0.95,
           'decay_lr': True,
           'decay_steps': 2000,
           'clip_global_norm': 1.0,
           'emb_dim': 512,
           'heads': 4,
           'mlp_dim': 512,
           'depth': 6,
           'rate':  0.1,
           'initializer': 'glorot_uniform'}
